name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # コードをチェックアウト
      - uses: actions/checkout@v4
      
      # Flutterをセットアップ
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      # 依存関係をインストール
      - name: Install dependencies
        run: |
          flutter --version
          flutter pub get
      
      # Webビルド（メモリ制限を緩和）
      - name: Build web
        run: |
          flutter clean
          flutter build web --release --no-tree-shake-icons
        env:
          FLUTTER_WEB_MAX_MEMORY: 4096
      
      # ビルド結果を確認
      - name: List build files
        run: ls -la build/web/
      
      # Netlify CLIをインストール
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      # Netlifyにデプロイ（直接Site IDを指定）
      - name: Deploy to Netlify
        run: |
          netlify deploy --prod \
            --dir=build/web \
            --site=delicate-vacherin-cd3cde \
            --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --message="Deploy from GitHub Actions: ${{ github.sha }}"
        timeout-minutes: 10